smith-chem-wisc/ProteoformSuite

ProteoformSuite/PS_0.00/ClassDiagram1.cd, ProteoformSuite/PS_0.00/ProteoformSuite.csproj, ProteoformSuite/PS_0.00/ProteomeDatabaseReader.cs, ProteoformSuite/ProteoformSuite.sln, ProteoformSuite/TasteTesting/ComponentTests.cs, ProteoformSuite/TasteTesting/Properties/AssemblyInfo.cs, ProteoformSuite/TasteTesting/TasteTesting.csproj, ProteoformSuite/TasteTesting/UnitTest1.cs, ProteoformSuite/UnitTestProject1/Properties/AssemblyInfo.cs, ProteoformSuite/UnitTestProject1/UnitTest1.cs, ProteoformSuite/UnitTestProject1/UnitTestProject1.csproj
See this walkthrough for more information: https://msdn.microsoft.com/en-us/library/ms182532.aspx.
Each test class should correspond to an object or a group of objects to test. Each class method in a unit test should test a method in that group. Each method consists of three parts: 1) "arrange:" set up the data, 2) "act:" run the method using that data, and 3) "assert" something about the result. These are only 3 lines in in the basic example I wrote, but they can be many more.
To add a unit test, right click the TasteTesting project -> Add -> Unit Test...
To run the tests, first build the solution, and then open Test Explorer from Test->Windows->Test Explorer. There is a "Run All" button to run the tests.
=> Basic unit test example, using method from Lollipop

PS_0.00/PS_0.00/Form1.cs, PS_0.00/PS_0.00/LoadDeconvolutionResults.cs
… when neucode labeled checkbox unchecked.
=> Implemented NeuCode toolstrip disable in DataTable-oriented code

ProteoformSuiteGUI/AggregatedProteoforms.cs, ProteoformSuiteGUI/DataGridViewDisplayUtility.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/NeuCodePairs.cs, ProteoformSuiteGUI/RawExperimentalComponents.cs, ProteoformSuiteGUI/SortableBindingList.cs, ProteoformSuiteGUI/TheoreticalDatabase.cs, ProteoformSuiteInternal/Lollipop.cs
Also, NeuCodePairs works more consistently. There were null objects being entered into the list, which is concerning; I simply removed those null elements for the time being.
=> Extended the sortable DataGridView display to the other Forms

ProteoformSuiteGUI/ProteoformFamilies.cs, ProteoformSuiteGUI/ProteoformSweet.Designer.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteInternal/Component.cs, ProteoformSuiteInternal/DeltaMassPeak.cs, ProteoformSuiteInternal/NeuCodePair.cs, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformRelation.cs, ProteoformSuiteInternal/Results.cs
-- namely of the results strings, using the new Result.cs class to host that all. Made some changes to the File and Folder dialogs, too.
=> Refactoring and reorganization 

ProteoformSuiteGUI/RawExperimentalComponents.cs, ProteoformSuiteInternal/Correction.cs, ProteoformSuiteInternal/ExcelReader.cs, ProteoformSuiteInternal/Lollipop.cs, Test/TestFindRawComponentsAndNeuCodePairs.cs
The code was comparing absolute file paths, which differed because of different extensions .xlsx and .tsv, so now it compares the filenames w/out the extensions
=> Fixed correction files/path issue

Examples/ptmlist.txt, ProteoformSuiteGUI/AggregatedProteoforms.Designer.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.Designer.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/LoadDeconvolutionResults.Designer.cs, ProteoformSuiteGUI/LoadDeconvolutionResults.cs, ProteoformSuiteGUI/NeuCodePairs.cs, ProteoformSuiteGUI/ProteoformSuiteGUI.csproj, ProteoformSuiteGUI/ProteoformSweet.Designer.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteInternal/Component.cs, ProteoformSuiteInternal/ExcelReader.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/ProteoformFamily.cs, ProteoformSuiteInternal/Results.cs
I think if anyone wants to use our software or if we want to use anything other than Thermo decon, it's easier if you can just format an excel file like the tsv output and upload that for the raw exp components.
=> fixed up buttons, can open raw exp comps only, fixed calibration

Examples/ptmlist.txt, ProteoformSuiteGUI/AggregatedProteoforms.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteGUI/Quantification.cs, ProteoformSuiteGUI/ResultsSummary.cs, ProteoformSuiteGUI/TheoreticalDatabase.Designer.cs, ProteoformSuiteGUI/TheoreticalDatabase.cs, ProteoformSuiteInternal/Component.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/NeuCodePair.cs, ProteoformSuiteInternal/Protein.cs, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteoformSuiteInternal.csproj, ProteoformSuiteInternal/ProteomeDatabaseReader.cs, ProteoformSuiteInternal/RandomExtensions.cs, ProteoformSuiteInternal/Results.cs, ProteoformSuiteInternal/goTerm.cs, Test/TestExperimentalProteoform.cs, Test/TestFindRawComponentsAndNeuCodePairs.cs, Test/TestProteoformCommunityRelate.cs, Test/TestProteoformFamilies.cs, Test/TestSaveAndLoadResults.cs
- similar to protein grouping when making theoretical proteoform databases
- fixed tests regarding component ID, intensity_sum vs. intensity_sum_olcs
=> Combining theoretical proteoforms by mass, 

ProteoformSuiteGUI/DisplayUtility.cs, ProteoformSuiteGUI/ExperimentExperimentComparison.Designer.cs, ProteoformSuiteGUI/ExperimentExperimentComparison.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.Designer.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/ProteoformSweet.Designer.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteGUI/RawExperimentalComponents.cs, ProteoformSuiteGUI/TheoreticalDatabase.cs, ProteoformSuiteInternal/DeltaMassPeak.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteomeDatabaseReader.cs, ProteoformSuiteInternal/Results.cs, Test/TestDeltaMassPeak.cs, Test/TestProteoformFamilies.cs
*need to open theoretical database for my BU experiments
*because ED was just random noise, the threshold is set by calculating the average random noise for a given peak width bin
=> open theoretical database + changed how threshold set/no more ED

ProteoformSuiteGUI/AggregatedProteoforms.cs, ProteoformSuiteGUI/ExperimentExperimentComparison.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/NeuCodePairs.cs, ProteoformSuiteGUI/ProteoformFamilies.Designer.cs, ProteoformSuiteGUI/ProteoformFamilies.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteGUI/RawExperimentalComponents.cs, ProteoformSuiteInternal/CytoscapeScript.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteoformFamily.cs
*Corrected modified theoretical display for Cytoscape. 
*Decimal rounding available for labels for Cytoscape display. 
*Improved timing for Cytoscape script. 
*Improved stability for opening form pages in wrong order.
=> Visualization & stability fixes

ProteoformSuiteGUI/DisplayUtility.cs, ProteoformSuiteGUI/ProteoformFamilies.cs, ProteoformSuiteInternal/CytoscapeScript.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteoformFamily.cs, ProteoformSuiteInternal/ProteoformRelation.cs
There is still some weirdness with the theoretical accessions not being unique.
=> Added more information to the ProteoformFamilies display.

Examples/default_method_load_and_run.txt, ProteoformSuiteGUI/AggregatedProteoforms.Designer.cs, ProteoformSuiteGUI/AggregatedProteoforms.cs, ProteoformSuiteGUI/DisplayUtility.cs, ProteoformSuiteGUI/ExperimentExperimentComparison.Designer.cs, ProteoformSuiteGUI/ExperimentExperimentComparison.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.Designer.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/LoadDeconvolutionResults.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteGUI/TheoreticalDatabase.Designer.cs, ProteoformSuiteInternal/DeltaMassPeak.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/NeuCodePair.cs, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteoformRelation.cs, ProteoformSuiteInternal/Results.cs, Test/Test.csproj, Test/TestDeltaMassPeak.cs, Test/TestLoadAndRun.cs, Test/TestProteoformFamilies.cs, Test/TestSaveAndLoadResults.cs
*peak threshold back to where user can set it. Still don't do ED/FDR because we don't use this for anything  (yet)
*changed it so you go to each page and can set params and then click the button to run it for the first time bc for label free it takes a long time to run everything and it would be nice to set it before it runs once through
=> debugged peak stuff, agg filters, changed GUI things

ProteoformSuiteGUI/ProteoformFamilies.cs, ProteoformSuiteGUI/Quantification.Designer.cs, ProteoformSuiteGUI/Quantification.cs, ProteoformSuiteInternal/CytoscapeScript.cs, ProteoformSuiteInternal/Proteoform.cs, Test/TestCytoscapeScript.cs, Test/TestProteoformCommunityRelate.cs
This is a needed fix, but now Cytoscape flakes out on loading parts of the node table (exp/theo/ptm) for no clear reason...
=> Cytoscape theoretical naming fix and testing

ProteoformSuiteGUI/ExperimentExperimentComparison.Designer.cs, ProteoformSuiteGUI/ExperimentExperimentComparison.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/ProteoformCommunity.cs
* I was getting a crash in constructing TheoreticalProteoformGroups with decoys of contaminants
=> Contaminant decoy fix

Mods/amino_acids.txt, Mods/intact_mods.txt, Mods/missing.txt, ProteoformSuiteGUI/ExperimentExperimentComparison.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/ProteoformFamilies.Designer.cs, ProteoformSuiteGUI/ProteoformFamilies.cs, ProteoformSuiteGUI/Quantification.Designer.cs, ProteoformSuiteGUI/Quantification.cs, ProteoformSuiteGUI/ResultsSummary.Designer.cs, ProteoformSuiteGUI/ResultsSummary.cs, ProteoformSuiteInternal/CytoscapeScript.cs, ProteoformSuiteInternal/ExperimentalProteoform.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/Modification.cs, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteoformFamily.cs, ProteoformSuiteInternal/ProteoformRelation.cs, ProteoformSuiteInternal/ResultsSummaryGenerator.cs, ProteoformSuiteInternal/TheoreticalProteoform.cs, ProteoformSuiteInternal/TheoreticalProteoformGroup.cs, Test/ConstructorsForTesting.cs, Test/TestCytoscapeScript.cs, Test/TestProteoformFamilies.cs, Test/TestSaveState.cs
See https://github.com/smith-chem-wisc/proteoform-suite/issues/310
Also fixed minor ET/EE bug: https://github.com/smith-chem-wisc/proteoform-suite/issues/333
=> Automatic identification of experimental nodes; final datatable of identified experimentals

ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/ProteoformRelation.cs
I had done this work on my laptop so I think I was too careless pushing from my work computer 👎
=> added back in 0.1 level dictionary for ptm sets

ProteoformSuiteInternal/DeltaMassPeak.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ProteoformRelation.cs, ProteoformSuiteInternal/SaveState.cs, Test/ConstructorsForTesting.cs, Test/TestProteoformCommunityRelate.cs, Test/TestProteoformFamilies.cs
Also changed peak building heuristic.
=> Fixed bug in setting ptm set rank sums in proteoform which caused ET relation inconsistencies

ProteoformSuiteGUI/ProteoformFamilies.Designer.cs, ProteoformSuiteGUI/ProteoformFamilies.cs, ProteoformSuiteInternal/Mods/intact_mods.txt, ProteoformSuiteInternal/Proteoform.cs, ProteoformSuiteInternal/ProteoformCommunity.cs
Also fixed a few bugs, including clearing families using the clear_families method rather than one that doesn't wipe the experimental identifications.
=> Modified some heuristics for a new (somewhat smaller) GPTMD database

ProteoformSuiteGUI/ExperimentExperimentComparison.cs, ProteoformSuiteGUI/ExperimentTheoreticalComparison.cs, ProteoformSuiteGUI/LoadDeconvolutionResults.Designer.cs, ProteoformSuiteGUI/LoadDeconvolutionResults.cs, ProteoformSuiteGUI/ProteoformSweet.Designer.cs, ProteoformSuiteGUI/ProteoformSweet.cs, ProteoformSuiteGUI/Quantification.cs, ProteoformSuiteGUI/RawExperimentalComponents.cs, ProteoformSuiteGUI/TheoreticalDatabase.Designer.cs, ProteoformSuiteGUI/TheoreticalDatabase.cs, ProteoformSuiteInternal/Lollipop.cs, ProteoformSuiteInternal/ProteoformCommunity.cs, ProteoformSuiteInternal/ResultsSummaryGenerator.cs, ProteoformSuiteInternal/Sweet.cs, Test/TestAggregationMethods.cs, Test/TestDeltaMassPeak.cs, Test/TestInputFile.cs, Test/TestSaveState.cs
=> mass shift and load method fixes

ProteoformSuiteInternal/Proteoform.cs, Test/TestProteoformIdentification.cs
Before we were just checking if this.ptmset contained the mod... I found a case where the set had more modifications than this.ptmset
=> ptm loss bug fix

ProteoWPFSuite/ProteoformFamilies.xaml.cs, ProteoWPFSuite/Quantification.xaml.cs
Removed initial MessageBoxes and Load can run without crashing
=> Last Pull T_T
